//
// Created by Harry on 9/11/2023.
//

#ifndef XLUA_METAMETHODHANDLERNUMBER_H
#define XLUA_METAMETHODHANDLERNUMBER_H
#include "MetaMethodHandler.h"

namespace LXX
{


class MetaMethodHandlerNumber :  public MetaMethodHandler
{
    OPERATOR_NEW_DELETE_OVERRIDE_ALL
public:
    MetaMethodHandlerNumber() ;
private:
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_ADD )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_SUB )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_MUL )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_DIV )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_MOD )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_POW )
    DECLARE_META_METHOD( META_METHOD_KEY_UNA_OP_MINUS )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_IDIV )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_BITWISE_AND )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_BITWISE_OR )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_BITWISE_XOR )
    DECLARE_META_METHOD( META_METHOD_KEY_UNA_OP_BITWISE_NOT )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_SHIFT_LEFT )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_SHIFT_RIGHT )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_CONCAT )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_EQUAL )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_LESS_THAN )
    DECLARE_META_METHOD( META_METHOD_KEY_BIN_OP_LESS_THAN_OR_EQUAL )
};


} // LXX

#endif //XLUA_METAMETHODHANDLERNUMBER_H
